from __future__ import annotations

BRONZE_COLUMNS = [
    "lake_image_id",
    "source_id",
    "source_name",
    "source_dataset_slug",
    "source_license",
    "source_site",
    "source_device",
    "source_notes",
    "image_id",
    "image_path",
    "resolved_image_path",
    "processed_image_path",
    "resolved_processed_image_path",
    "original_path",
    "label_original",
    "patient_id",
    "patient_id_source",
    "study_id",
    "ear_side",
    "age",
    "sex",
    "quality",
    "sha256",
    "raw_sha256",
    "processed_sha256",
    "width",
    "height",
    "processed_width",
    "processed_height",
]

SILVER_COLUMNS = [
    *BRONZE_COLUMNS,
    "label_standard",
    "label_mapping_status",
    "image_exists",
    "processed_image_exists",
    "duplicate_raw_sha256",
    "duplicate_processed_sha256",
    "split_group",
]

GOLD_COLUMNS = [
    "image_id",
    "image_path",
    "patient_id",
    "label",
    "source_id",
    "source_name",
    "site",
    "device",
    "ear_side",
    "age",
    "sex",
    "quality",
    "patient_id_source",
    "study_id",
    "raw_sha256",
    "processed_sha256",
    "width",
    "height",
    "processed_width",
    "processed_height",
    "split_group",
]

