import { auth } from '@/firebase.config';
import {
  AI_MODEL_STORAGE_KEY,
  DEFAULT_AI_MODEL_ID,
  isValidAIModelId,
} from '@/lib/aiModels';

function getSelectedModelId() {
  if (typeof window === 'undefined') {
    return DEFAULT_AI_MODEL_ID;
  }

  const storedModelId = window.localStorage.getItem(AI_MODEL_STORAGE_KEY);
  return isValidAIModelId(storedModelId) ? storedModelId : DEFAULT_AI_MODEL_ID;
}

export const createProfile = async (fileList) => {
  const formData = new FormData();

  fileList.forEach((file) => {
    formData.append('images', file.originFileObj);
  });

  const randomNumber = Math.floor(1000 + Math.random() * 9000);
  const autoGeneratedName = `#${randomNumber}`;
  formData.append('name', autoGeneratedName);
  formData.append('modelId', getSelectedModelId());

  try {
    const user = auth?.currentUser;
    let headers = {};

    if (user) {
      const token = await user.getIdToken();
      headers = {
        Authorization: `Bearer ${token}`,
      };
    }

    const response = await fetch('/api/create-profile', {
      method: 'POST',
      headers,
      body: formData,
    });

    if (!response.ok) {
      throw new Error('Failed to create profile');
    }

    return await response.json();
  } catch (error) {
    throw new Error(error.message || 'Something went wrong during profile creation');
  }
};
